import numpy as np

from uso.sent_packet import uso_dtype, uso_bitfield_names


def create_packet(lamps_state):
    uso_packet = np.zeros(1, dtype=uso_dtype)    
    uso_packet["bitfield"] = np.packbits(lamps_state, bitorder="little")
    return uso_packet


uso_lamp_send_map = {
    "O10_a12": "pty_lh", # PTY стрелка OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [22 Пульт козырька левый]
    "O10_a13": "pty_lh", # PTY надпись OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [22 Пульт козырька левый]
    "O10_a14": "master_warning_lh", # MASTER WARNING light OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [22 Пульт козырька левый]
    "O10_a15": "master_caution_lh", # MASTER CAUTION light OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [22 Пульт козырька левый]
    "O10_a16": "pty_rh", # PTY стрелка OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [23 Пульт козырька правый]
    "O10_a17": "pty_rh", # PTY надпись OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [23 Пульт козырька правый]
    "O10_a18": "master_warning_rh", # MASTER WARNING light OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [23 Пульт козырька правый]
    "O10_a19": "master_caution_rh", # MASTER CAUTION light OUT [K2 Средний пульт (Pedestal)] [Козырек приборной доски] [23 Пульт козырька правый]
	# "O10_a04",	# 115/230 индикатор [K2 Средний пульт (Pedestal)] [Приборная доска] [03 - 15 Рукоятка аварийного/стояночного тормоза (#--#) - Кнопка-переключатель 115/220]
	# "O26_a32",	# DIM [K2 Средний пульт (Pedestal)] [Приборная доска] [03 - 15 Рукоятка аварийного/стояночного тормоза (#--#) - Кнопка-переключатель 115/220]
	# "O26_a30",	# TEST [K2 Средний пульт (Pedestal)] [Приборная доска] [03 - 15 Рукоятка аварийного/стояночного тормоза (#--#) - Кнопка-переключатель 115/220]
	# "O10_a01",	# РУД 3 лампы <red light> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [01 Сборка РУД]
	# "O10_a02",	# РУД 3 лампы <red light> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [01 Сборка РУД]
	# "O10_a03",	# РУД 3 лампы <red light> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [01 Сборка РУД]
	# "O10_a05",	# AURAL WARN 1 OUT <OFF> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	# "O10_a06",	# AURAL WARN 1 OUT <OFF> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	# "O10_a07",	# BAG FAN OUT <ON> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	# "O10_a08",	# ELEC RH ESS OUT <ISOL> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	# "O10_a09",	# FUEL 2 B/U OUT <INHIBIT> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	# "O10_a10",	# RAT AUTO OUT <ON> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	# "O10_a11",	# TRIM EMERG OUT <ON> [K2 Средний пульт (Pedestal)] [Средний пульт (Pedestal)] [12  (Emergency Panel)]
	"O10_a20": "firebutton_1",	# engine 1 shut off FIRE <CLOSED> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a21": "disch1_eng1_1",	# engine 1 DISCH 1 <1> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a22": "disch1_eng1",	# engine 1 DISCH 1 <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a23": "disch2_eng1_1",	# engine 1 DISCH 2 <1> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a24": "disch2_eng1",	# engine 1 DISCH 2 <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a25": "apu_disch",	# FIRE APU <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a26": "fire_apu_closed_indicator",	# FIRE APU <CLOSED> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a27": "firebutton_2",	# engine 2 shut off FIRE 2 <CLOSED> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a28": "disch1_eng2_1",	# engine 2 DISCH 1 <1> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a29": "disch1_eng2",	# engine 2 DISCH 1 <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a30": "disch2_eng2_1",	# engine 2 DISCH 2 <1> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a31": "disch2_eng2",	# engine 2 DISCH 2 <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_a32": "firebutton_3",	# engine 3 shut off FIRE 3 <CLOSED> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b01": "disch1_eng3_1",	# engine 3 DISCH 1 <1> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b02": "disch1_eng3",	# engine 3 DISCH 1 <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b03": "disch2_eng3_1",	# engine 3 DISCH 2 <1> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b04": "disch2_eng3",	# engine 3 DISCH 2 <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b05": "firerearcomp_button",	# FIRE REAR COMP DISCH <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b06": "firebagcomp_button",	# FIRE BAG COMP DISCH <DISCH> [K4 Верхний пульт] [Верхний пульт] [01 (Fire Control Panel) Пульт пожарной сигнализации]
	"O10_b07": "airbrake_auto",	# AJB AUTO EXT. <OFF> [K4 Верхний пульт] [Верхний пульт] [02 - 03 FLIGHT CONTROL  - STEERING FL CON]
	"O10_b08": "fcs_engage_norm",	# FCS ENGAGE NORM <?????> [K4 Верхний пульт] [Верхний пульт] [02 - 03 FLIGHT CONTROL  - STEERING FL CON]
	"O10_b09": "fcs_engage_stby",	# FCS ENGAGE ST-BY <?????> [K4 Верхний пульт] [Верхний пульт] [02 - 03 FLIGHT CONTROL  - STEERING FL CON]
	"O10_b10": "fcs_steering",	# NWS <OFF> [K4 Верхний пульт] [Верхний пульт] [02 - 03 FLIGHT CONTROL  - STEERING FL CON]
	"O10_b11": "apu_master",	# APU Master <ON> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b12": "apu_start_stop",	# APU Start / Stop <RUN> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b13": "shutoff_a1",	# SHUT OFF A1 <CLOSE> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b14": "shutoff_a3",	# SHUT OFF A3 <CLOSE> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b15": "shutoff_b2",	# SHUT OFF B2 <CLOSE> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b16": "shutoff_b3",	# SHUT OFF B3 <CLOSE> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b17": "shutoff_c2",	# SHUT OFF C2 <CLOSE> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b18": "backup_pump_on",	# BACK UP PUMP <ON> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b19": "backup_pump_off",	# BACK UP PUMP <OFF> [K4 Верхний пульт] [Верхний пульт] [04 - 05 - 06 Engines Manual Start - APU control panel - HYDROLYCS]
	"O10_b27": "cabin_master_on",	# CABIN MASTER <SHEO> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_b28": "cabin_master_off",	# CABIN MASTER <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_b29": "rh_master",	# RH MASTER <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_b30": "rh_init",	# RH INIT <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_b31": "bus_tie",	# BUS TIE <TIED> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_b32": "lh_init",	# LH INIT <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c01": "lh_master",	# LH MASTER <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c02": "rh_isol",	# RH ISOL <ISOL> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c03": "galley_master_off",	# GALLEY MASTER <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c04": "gen2",	# GEN 2 <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c05": "galley_master_on",	# GALLEY MASTER <SHEO> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c06": "gen3",	# GEN 3 <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c07": "gen1",	# GEN  1 <OFF> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c08": "ext_power",	# EXT POWER <BUTTON> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c09": "lh_isol",	# LH ISOL <ISOL> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c10": "ice_wings_on",	# WINGS <ON> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c11": "ice_wings_stby",	# WINGS <ST-BY> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c12": "ice_brake",	# BRAKE <ON> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c13": "ice_eng1",	# ENG 1 <ON> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c14": "ice_eng2_on",	# ENG 2 <ON> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c15": "ice_eng2_stby",	# ENG 2 <ST-BY> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_c16": "ice_eng3",	# ENG 3 <ON> [K4 Верхний пульт] [Верхний пульт] [07 - 09 DC SUPPLY (Electrical System control panel) - ANTI-ICE]
	"O10_b24": "bag_isol",	# BAG ISOL <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_b25": "xbleed_ecs_on",	# XBLEED ECS <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_b26": "xbleed_ecs_off",	# XBLEED ECS <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_b20": "fwd_temp_push",	# PAX AFT TEMP <INOP> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_b21": "fwd_temp_push",	# PAX FWD TEMP <MAN> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_b22": "crew_temp_push",	# CREW TEMP <MAN> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_b23": "gnd_vent",	# GND VENT <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c17": "bleed1_off",	# BLEED 1 <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c18": "bleed1_hpoff",	# BLEED 1 <HP OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c19": "bleed12_off",	# XBLEED 1--2 <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c20": "bleed12_on",	# XBLEED 1--2 <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c21": "bleed2_hpoff",	# BLEED 2 <HP OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c22": "bleed2_off",	# BLEED 2 <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c23": "bleed13_on",	# XBLEED 2--3 <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c24": "bleed13_off",	# XBLEED 2--3 <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c25": "bleed_apu_on",	# BLEED APU <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c26": "bleed_apu_off",	# BLEED APU <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c27": "bleed3_hpoff",	# BLEED 3 <HP OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c28": "bleed3_off",	# BLEED 3 <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c29": "dump",	# DUMP <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c30": "bag_vent_on",	# BAG VENT <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c31": "bag_vent_off",	# BAG VENT <OFF> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O10_c32": "pressu_man",	# PRESSU MAN <ON> [K4 Верхний пульт] [Верхний пульт] [08 AIR CONDITION - BLEED - Pressurization   Bleed control panel Pressurization control panel]
	"O11_a10": "boost1_off",	# BOOST 1 <OFF> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a11": "boost1_stby",	# BOOST 1 <ST-BY> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a12": "boost2_off",	# BOOST 2 <OFF> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a13": "boost2_stby",	# BOOST 2 <ST-BY> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a14": "boost3_off",	# BOOST 3 <OFF> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a15": "rh_master",	# RH MASTER <OFF> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a16": "boost3_stby",	# BOOST 3 <ST-BY> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a17": "xbp_12",	# X-BP 1<-->2  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a18": "xbp_13",	# X-BP 1<-->3  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a19": "xbp_23",	# X-BP 2<-->3  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a20": "xtk_down_1",	# XTK DOWN 1  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a21": "xtk_down_2",	# XTK DOWN 2  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a22": "xtk_left",	# XTK LEFT 1  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a23": "xtk_right",	# XTK RIGHT 1  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a24": "xtk_up_1",	# XTK UP 1  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a25": "xtk_up_2",	# XTK UP 2  <ON> [K4 Верхний пульт] [Верхний пульт] [10 Fuel System control panel]
	"O11_a01": "probe_12",	# PROBE 1+2 <OFF> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a02": "probe_3",	# PROBE 3 <OFF> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a03": "probe_4",	# PROBE 4 <OFF> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a04": "windshield_lh_off",	# LH <OFF> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a05": "windshield_lh_max",	# LH <MAX> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a06": "windshield_rh_off",	# RH <OFF> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a07": "windshield_rh_max",	# RH <MAX> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a08": "windshield_backup_max",	# BACK UP <MAX LH> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a09": "windshield_backup_off",	# BACK UP  <MAX RH> [K4 Верхний пульт] [Верхний пульт] [11 - 12 - 13 WINDSHEILD HEAT - PILOT HEAT - PAX OXYGEN]
	"O11_a26": "el_nav_logo",	# NAV <LOGO> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_a27": "el_nav_off",	# NAV <OFF> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_a28": "el_anticol_off",	# ANTICOL <OFF> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_a29": "el_anticol_red",	# ANTICOL <RED> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_a30": "el_wing",	# WINGS <OFF> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_a31": "el_taxi",	# TAXI <ON> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_a32": "el_landing_lh",	# SWITCH LANDING 1 <LDG> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_b01": "el_landing_rh",	# SWITCH LANDING 2 <LDG> [K4 Верхний пульт] [Верхний пульт] [15 EXTERIOR LIGHTS + RAIN RPLNT LH]
	"O11_b02": "il_cabin_pax",	# CABIN <PAX> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b03": "il_fasten",	# FASTEN BELT <ON> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b04": "il_smoking",	# NO SMOKING <ON> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b05": "il_cabin_off",	# CABIN <OFF> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b06": "il_emerge_lights_on",	# SWITCH <EMERG LIGHTS> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
    "O11_b07": "fireindicator_1",	# engine 1 shut off FIRE <red light> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b08": "fire_apu_indicator",	# FIRE APU <red light> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b09": "fireindicator_2",	# engine 2 shut off FIRE 2 <red light> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b10": "firerearcomp_indicator",	# FIRE REAR COMP DISCH <red light> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b11": "firebagcomp_indicator",	# FIRE BAG COMP DISCH <red light> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
	"O11_b12": "fireindicator_3",	# engine 3 shut off FIRE 3 <red light> [K4 Верхний пульт] [Верхний пульт] [16 - 17 COCKPIT LIGHTS - INTERIOR LIGHTS + RAIN RPLNT RH]
}


# replace lamps bit ids with indecies
temp_map = {}
for bit_id, lamp_id in uso_lamp_send_map.items():
    idx = uso_bitfield_names.index(bit_id)
    temp_map[idx] = lamp_id

uso_lamp_send_map = temp_map
del temp_map
